#server:
#  ssl:
#    enabled: ${SSL_ENABLED:false}
#    hsts-enabled: ${SSL_HSTS_ENABLED:true}
#    key-store: ${SSL_KEYSTORE:classpath:keystore.jks}
#    key-store-password: ${SSL_KEYSTORE_PASSWORD:ssl-password-not-specified}
#    key-alias: ${SSL_KEY_ALIAS:tomcat}
#    key-password: ${SSL_KEY_PASSWORD:tomcat-password-not-specified}

#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: ${CRACKSHOT_SPRING_PROFILE:production}

security:
  cors.origin: '*'
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAltt/MzKpEH7BXhGEoRwj
          np+M8WP0pLZIoa4Izvq9fmt3c7GwGswRh7SHGQbPIOA+dKwJjUO5lrN8LZ/2eSrC
          RLj9cU/4WKT+KoEgPneZHJgHwaoxKUA5tZWjTjNQKiMdHK42ExbE/8HTS4ODfJIW
          6bOBIqiPtqilbCB1DgoOmA9lNGuj0N+n2RJWBM39sKTTC+HK5WTMudQB3xaNlJhO
          KUa6guYzK6j11Gh3kSpY+x9Rlz8KO5HVbNiT50pY0sgZYJhwh5NUceU5IZgjRxuH
          4mWeNVaz/F6hACN34y/R8uPfcvKXCfEyhDeR8qH9KZ6jmJclJzcyNksFh6EwN+G2
          kQIDAQAB
          -----END PUBLIC KEY-----

stx:
  crackshot:
    admin_role: ${CRACKSHOT_ADMIN_ROLE:Crackshot admins}
  rest:
    admin:
      username: ${REST_ADMIN_USERNAME:admin}
      email: ${REST_ADMIN_EMAIL:admin@startext.ru}

---
spring:
  profiles: production

  datasource:
    driverClassName: ${REST_DB_DRIVER:org.h2.Driver}
    url: ${REST_DB_URL:jdbc:h2:file:~/auk-crackshot}
    username: ${REST_DB_USERNAME:sa}
    password: ${REST_DB_PASSWORD:}
  jpa:
    database-platform: ${REST_DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${REST_DB_DDL_AUTO:update}

---
spring:
  profiles: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/auk-crackshot
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
