version: "3.5"

services:
  crackshot-app:
    entrypoint:
      - catalina.sh
      - jpda
      - run
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    ports:
      - "8000:8000"
