version: "3.5"
services:
  rest:
    container_name: crackshot
    image: registry.startext.ru/auk/crackshot:develop
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env_rest
    volumes:
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    networks:
      - crackshot

networks:
  crackshot:
